FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ${ROOT_PROJECT} .

ENV FLASK_APP=run:flask_app
ENV FLASK_ENV=docker

EXPOSE 5050

CMD ["flask", "run", "--host=0.0.0.0", "--port=5050"]